accessKey: myaccesskey
secretKey: mysecretkey
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
persistence:
  enabled: true
  storageClassName: standard
  accessMode: ReadWriteOnce
  size: 10Gi

